---

name: lint-code-base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: lint-code-base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: checkout-code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      ################################
      # Run Linter against code base #
      ################################
      - name: lint-code-base
        run: |
          make lint
